export const data = [
    {
        "year":"2000",
        "population":1
    },
    {
        "year":"2001",
        "population":2
    },
    {
        "year":"2002",
        "population":3
    },
    {
        "year":"2003",
        "population":4
    },
    {
        "year":"2004",
        "population":5
    },
    {
        "year":"2005",
        "population":4
    },
    {
        "year":"2006",
        "population":7
    },
    {
        "year":"2007",
        "population":3
    },
    {
        "year":"2008",
        "population":8
    },
    {
        "year":"2009",
        "population":1
    },
    {
        "year":"2010",
        "population":2
    },
    {
        "year":"2011",
        "population":5
    },
    
]